fixtures:
  repositories:
    collectd: https://github.com/camptocamp/puppet-collectd.git
  forge_modules:
    concat: 'puppetlabs-concat'
    stdlib: 'puppetlabs-stdlib'
  symlinks:
    apache_c2c: "#{source_dir}"
